// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpineFeedbackScreenshot } from "./SpineFeedbackScreenshot";

export type SpineFeedbackUploadParams = { threadId: string, note?: string | null, screenshots?: Array<SpineFeedbackScreenshot> | null, };
