// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpineTreeNode } from "./SpineTreeNode";

export type SpineTreeUpdatedNotification = { threadId: string, turnId: string, snapshotSeq: bigint, activeNodeId: string, nodes: Array<SpineTreeNode>, settledSpawnCallIds: Array<string>, };
