// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabAgentStatus } from "./CollabAgentStatus";

export type SpineSpawnTaskProgress = { ordinal: number, summary: string, threadId: string, agentPath: string | null, status: CollabAgentStatus, };
