// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpineNodeContextPressureProblem = "missing_current_usage" | "missing_open_context_baseline" | "coordinate_mismatch";
