// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpineNodeContextPressureProblem } from "./SpineNodeContextPressureProblem";

export type SpineNodeContextPressure = { openInputTokens: bigint | null, currentInputTokens: bigint | null, contextTokens: bigint | null, problem: SpineNodeContextPressureProblem | null, };
