// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpineSpawnTaskProgress } from "./SpineSpawnTaskProgress";

/**
 * Live-only progress for an experimental `spine.spawn` transaction.
 */
export type SpineSpawnProgressUpdatedNotification = { threadId: string, turnId: string, callId: string, tasks: Array<SpineSpawnTaskProgress>, };
