//! Spine-owned session snapshots and compatibility inputs for pre-0.4 config locks.
use crate::config_toml::ConfigToml;
use codex_utils_absolute_path::AbsolutePathBuf;
use schemars::JsonSchema;
use serde::Deserialize;
use serde::Serialize;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, JsonSchema)]
#[schemars(deny_unknown_fields)]
pub struct ConfigLockfileToml {
    pub version: u32,
    pub codex_version: String,

    /// Complete Spine SDK source ledger used to build the effective session
    /// configuration. Version-1 lockfiles omit this field.
    #[serde(default)]
    pub spine_config: Option<SpineConfigLockToml>,

    /// Replayable effective config captured in the lockfile.
    pub config: ConfigToml,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, JsonSchema)]
#[schemars(deny_unknown_fields)]
pub struct SpineConfigLockToml {
    pub schema_version: u32,
    pub bundled_digest: String,
    pub sources: Vec<SpineConfigSourceLockToml>,
    /// Complete SDK configuration; version 3 no longer reads mutable source files on replay.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_config: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, JsonSchema)]
#[schemars(deny_unknown_fields)]
pub struct SpineConfigSourceLockToml {
    pub path: AbsolutePathBuf,
    pub required: bool,
    /// SHA-256 digest of the source bytes, or `None` when an optional
    /// candidate did not exist while the lock was created.
    pub digest: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default, PartialEq, Eq, JsonSchema)]
#[schemars(deny_unknown_fields)]
pub struct DebugToml {
    pub config_lockfile: Option<DebugConfigLockToml>,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default, PartialEq, Eq, JsonSchema)]
#[schemars(deny_unknown_fields)]
pub struct DebugConfigLockToml {
    /// Directory where Codex writes effective session config lock files.
    pub export_dir: Option<AbsolutePathBuf>,

    /// Lockfile to replay as the authoritative effective config.
    pub load_path: Option<AbsolutePathBuf>,

    /// Allow replaying a lock generated by a different Codex version.
    pub allow_codex_version_mismatch: Option<bool>,

    /// Save fields resolved from the model catalog/session configuration.
    pub save_fields_resolved_from_model_catalog: Option<bool>,
}

impl ConfigToml {
    pub fn spine_snapshot_settings(&self) -> Option<&DebugConfigLockToml> {
        match (&self.spine_snapshot, &self.debug) {
            (Some(settings), _) => Some(settings),
            (None, Some(legacy)) => legacy.config_lockfile.as_ref(),
            (None, None) => None,
        }
    }
}
